# Generated by Django 4.1 on 2022-09-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Content', help_text='Leave it as it is.', max_length=7, null=True, verbose_name='Name')),
                ('about_par_1', models.TextField(blank=True, help_text='About page first paragraph', null=True, verbose_name='About Info Paragraph 1')),
                ('about_par_2', models.TextField(blank=True, help_text='About page second paragraph', null=True, verbose_name='About Info Paragraph 2')),
                ('city_country', models.CharField(blank=True, help_text='City, Country (Address)', max_length=50, null=True, verbose_name='City, Country')),
                ('address', models.CharField(blank=True, max_length=75, null=True, verbose_name='Street Number, Name, other')),
                ('email', models.EmailField(blank=True, help_text='Your email for contact info', max_length=254, null=True, verbose_name='Your Email')),
                ('phone_1', models.CharField(blank=True, help_text='Your phone for contact info. Do the formatting here (e.g. +1 (438) 777 7777', max_length=20, null=True, verbose_name='Telephone')),
                ('phone_2', models.CharField(blank=True, help_text='Your Second phone for contact info. Do the formatting here (e.g. +1 (438) 777 7777)', max_length=20, null=True, verbose_name='Telephone')),
                ('intro_text', models.TextField(blank=True, help_text="Text underneath 'Kane'", null=True, verbose_name='Intro Text')),
                ('services_text', models.TextField(blank=True, help_text="Text underneath 'Services' (home page)", null=True, verbose_name='Text for services')),
                ('latest_projects_text', models.TextField(blank=True, help_text="Text underneath 'Latest Projects' (home page)", null=True, verbose_name='Text for latest projects')),
                ('twitter_link', models.URLField(blank=True, help_text='Contact info', null=True, verbose_name='Twitter Link')),
                ('ig_link', models.URLField(blank=True, help_text='Contact Info', null=True, verbose_name='Instagram Link')),
                ('linkedin_link', models.URLField(blank=True, help_text='Contact Info', null=True, verbose_name='LinkedIn Link')),
                ('footer_desc_par_1', models.CharField(blank=True, help_text='Paragraph 1, Max one sentence', max_length=150, null=True, verbose_name='Footer Short Description 1')),
                ('footer_desc_par_2', models.CharField(blank=True, help_text='Paragraph 2, Max one sentence', max_length=150, null=True, verbose_name='Footer Short Description 2')),
                ('hide_info', models.BooleanField(default=False, help_text='Hide all information', verbose_name='Hide all info')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30, verbose_name='Subject')),
                ('service', models.CharField(max_length=30, verbose_name='Service Type')),
                ('budget', models.CharField(blank=True, max_length=20, null=True, verbose_name='Budget')),
                ('message', models.TextField(verbose_name='Message')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Personal Notes')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-inquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_name', models.CharField(help_text='Name of the service you provide', max_length=30, primary_key=True, serialize=False, verbose_name='Service Name')),
                ('short_description', models.CharField(help_text='Short Description', max_length=200, verbose_name='Short Description')),
                ('description', models.TextField(help_text='Detailed Description', verbose_name='Description')),
                ('icon', models.FileField(help_text='MUST BE .SVG EXTENSIONS', upload_to='photos/services/', verbose_name='Icon')),
                ('main_img', models.ImageField(upload_to='photos/services/', verbose_name='Main Img')),
                ('hide', models.BooleanField(default=False, help_text='Check to hide service', verbose_name='Hide Service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the project', max_length=30, verbose_name='Project Name')),
                ('date', models.DateField(blank=True, help_text='Date when the event took place', null=True, verbose_name='Date of the Event')),
                ('description_1', models.TextField(help_text='Event Description', verbose_name='Description, Paragraph 1')),
                ('description_2', models.TextField(blank=True, help_text='Event Description', null=True, verbose_name='Description, Paragraph 2')),
                ('description_3', models.TextField(blank=True, help_text='Event Description', null=True, verbose_name='Description, Paragraph 3')),
                ('press_link', models.URLField(blank=True, help_text='Link for Press Article', null=True, verbose_name='Press Link')),
                ('fb_link', models.URLField(blank=True, help_text='Facebook Link for More', null=True, verbose_name='Facebook Link')),
                ('ig_link', models.URLField(blank=True, help_text='Instagram Link for More', null=True, verbose_name='Instagram Link')),
                ('twitter_link', models.URLField(blank=True, help_text='Twitter Link for More', null=True, verbose_name='Twitter Link')),
                ('linkedin_link', models.URLField(blank=True, help_text='LinkedInLink for More', null=True, verbose_name='LinkedIn Link')),
                ('hide', models.BooleanField(default=False, help_text='Check to hide item', verbose_name='Hide Item')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='photos/portfolio/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='photos/portfolio/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='photos/portfolio/')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='photos/portfolio/')),
                ('img_5', models.ImageField(blank=True, null=True, upload_to='photos/portfolio/')),
                ('service_category', models.ForeignKey(help_text='Type of the service', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='home.services')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
            },
        ),
    ]
