# Generated by Django 4.1 on 2024-03-19 16:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_content_fb_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='about_par_2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='footer_desc_par_2',
        ),
        migrations.AddField(
            model_name='content',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='Contact info', null=True, verbose_name='Spotify Link'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='Twitter Link for More', null=True, verbose_name='Spotify Link'),
        ),
        migrations.AlterField(
            model_name='content',
            name='about_par_1',
            field=tinymce.models.HTMLField(blank=True, help_text='About page first paragraph', null=True, verbose_name='About Info Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='content',
            name='footer_desc_par_1',
            field=models.TextField(blank=True, help_text='Paragraph 1, Max one sentence', max_length=200, null=True, verbose_name='Footer Short Description 1'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_1',
            field=tinymce.models.HTMLField(help_text='Event Description', verbose_name='Description, Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_2',
            field=tinymce.models.HTMLField(blank=True, help_text='Event Description', null=True, verbose_name='Description, Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_3',
            field=tinymce.models.HTMLField(blank=True, help_text='Event Description', null=True, verbose_name='Description, Paragraph 3'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=tinymce.models.HTMLField(help_text='Detailed Description', verbose_name='Description'),
        ),
    ]
