# Generated by Django 4.0 on 2024-12-03 03:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_content_footer_desc_par_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='short_description',
            field=tinymce.models.HTMLField(help_text='Short Description', verbose_name='Short Description'),
        ),
    ]
