# Generated by Django 4.0 on 2024-12-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_services_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='spotify_link',
        ),
    ]
