# Generated by Django 4.0 on 2025-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_portfolioitem_spotify_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='front_image',
            field=models.ImageField(help_text='Square Image', null=True, upload_to='photos/portfolio/', verbose_name='Front Image'),
        ),
    ]
