# Generated by Django 4.0 on 2025-02-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_portfolioitem_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='Spotify Link', null=True, verbose_name='Spotify Link'),
        ),
    ]
